# -*- coding: utf-8 -*-
"""tribev2 tests

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MeS3PmPaq5OSWAPMFPGh77tdOldXGdwZ
"""


# # Download the YouTube short
# import subprocess
# url = "https://www.youtube.com/shorts/3YxtTAMNJhM"
# output_path = "video.mp4"
# subprocess.run(["yt-dlp", "-o", output_path, url], check=True)

# from tribev2.demo_utils import TribeModel

# model = TribeModel.from_pretrained("facebook/tribev2", cache_folder="./cache")

# df = model.get_events_dataframe(video_path="video.mp4.webm")
# print(df.head())

# df.to_csv("events.csv")

# import pandas as pd

# df = pd.read_csv('events.csv')

# df_short = df[df['start'] < 60]
# print(df_short.head())

# from tribev2 import TribeModel
# import torch

# model = TribeModel.from_pretrained("facebook/tribev2", cache_folder="./cache")

# # TribeModel wraps a Lightning module; find where FmriEncoder lives
# print(type(model))
# print(dir(model))  # look for: model, pl_module, brain_model, experiment, etc.

# # Step 1: trigger model setup so the Lightning module gets instantiated
# model.setup_run()

# # Then inspect what setup_run created on the object
# # Look for anything new that appeared, specifically nn.Module attributes
# import torch.nn as nn
# for attr in dir(model):
#     if not attr.startswith('_'):
#         try:
#             val = getattr(model, attr)
#             if isinstance(val, nn.Module):
#                 print(f"{attr}: {type(val)}")
#         except Exception:
#             pass

# # Step 2: check the private attributes, which Pydantic stores separately
# print(model.__pydantic_private__)
# print(model.__dict__)

import torch
import numpy as np
from collections import defaultdict
from tribev2 import TribeModel

# ── Access the nn.Module ──────────────────────────────────────────────────────
model = TribeModel.from_pretrained("facebook/tribev2", cache_folder="./cache")
fmri_enc = model.__pydantic_private__['_model']   # FmriEncoderModel
fmri_enc.eval()

# ── Register hooks ────────────────────────────────────────────────────────────
features = defaultdict(list)
hooks = []

def make_hook(name):
    def hook(module, input, output):
        out = output[0] if isinstance(output, tuple) else output
        features[name].append(out.detach().cpu())
    return hook

# Modality projectors (output shape: (batch, time, 384) each)
for modality in ['text', 'audio', 'video']:
    m = fmri_enc.projectors[modality]
    hooks.append(m.register_forward_hook(make_hook(f'projector.{modality}')))

# Each transformer layer: even indices = Attention, odd = FeedForward
# encoder.layers[i][1] is the actual module (index [0] is the norm, [2] is Residual)
for i, layer_block in enumerate(fmri_enc.encoder.layers):
    submodule = layer_block[1]  # Attention or FeedForward
    layer_type = 'attn' if i % 2 == 0 else 'ffn'
    transformer_layer_idx = i // 2  # 0-7
    name = f'encoder.layer{transformer_layer_idx}.{layer_type}'
    hooks.append(submodule.register_forward_hook(make_hook(name)))

# Final norm, low-rank head, and predictor
hooks.append(fmri_enc.encoder.final_norm.register_forward_hook(make_hook('encoder.final_norm')))
hooks.append(fmri_enc.low_rank_head.register_forward_hook(make_hook('low_rank_head')))
hooks.append(fmri_enc.predictor.register_forward_hook(make_hook('predictor')))

print(f"Registered {len(hooks)} hooks")

# ── Run inference ─────────────────────────────────────────────────────────────
#df = model.get_events_dataframe(video_path="path/to/video.mp4")

with torch.no_grad():
    preds, segments = model.predict(events=df_short)

# ── Remove hooks and save ─────────────────────────────────────────────────────
for h in hooks:
    h.remove()

for layer_name, tensors in features.items():
    stacked = torch.cat(tensors, dim=0)
    safe_name = layer_name.replace('.', '_')
    np.save(f"features_{safe_name}.npy", stacked.numpy())
    print(f"  {layer_name:40s}  shape={tuple(stacked.shape)}")

all_features_dict = {}
for layer_name, tensors in features.items():
    stacked = torch.cat(tensors, dim=0)
    safe_name = layer_name.replace('.', '_')
    all_features_dict[safe_name] = stacked.numpy()
    print(f"  {layer_name:40s}  shape={{tuple(stacked.shape)}}")

np.savez_compressed("all_features.npz", **all_features_dict)
print("All features saved to all_features.npz")

preds, segments = model.predict(events=df_short)
print(f"Predictions shape: {preds.shape}  (n_timesteps, n_vertices)")

import numpy as np

np.savez_compressed('video.npz',preds=preds,segments=segments,df=df_short.to_numpy())

# """# Visualization"""

# from tribev2.plotting import PlotBrain
# from pathlib import Path

# CACHE_FOLDER = Path("./cache")

# model = TribeModel.from_pretrained(
#     "facebook/tribev2",
#     cache_folder=CACHE_FOLDER,
# )
# plotter = PlotBrain(mesh="fsaverage5")

# n_timesteps = 15
# fig = plotter.plot_timesteps(preds[:n_timesteps], segments=segments[:n_timesteps], cmap="fire", norm_percentile=99, vmin=.6, alpha_cmap=(0, .2), show_stimuli=True)

"""# Finetuning the brain encoding layer"""
""" 
import torch
import torch.nn as nn
from tribev2 import TribeModel

# ── Access the nn.Module ──────────────────────────────────────────────────────
model = TribeModel.from_pretrained("facebook/tribev2", cache_folder="./cache")
fmri_enc = model.__pydantic_private__['_model']   # FmriEncoderModel

# ── Choose your target ────────────────────────────────────────────────────────
# Options (use the string that matches named_parameters() prefixes):
#   "predictor"              subject head (best for new-subject fine-tuning)
#   "low_rank_head"          low-rank projection before subject head
#   "encoder.layers.14"      last attention block  (encoder layer 7, attn)
#   "encoder.layers.15"      last FFN block        (encoder layer 7, FFN)
#   "projectors.text"        text modality projector
#   "projectors.audio"       audio modality projector
#   "projectors.video"       video modality projector

TRAINABLE_LAYER = "predictor"   # ← change as needed

# ── Freeze everything ─────────────────────────────────────────────────────────
for param in fmri_enc.parameters():
    param.requires_grad = False

# ── Un-freeze only the target layer ──────────────────────────────────────────
unfrozen = 0
for name, param in fmri_enc.named_parameters():
    if name.startswith(TRAINABLE_LAYER):
        param.requires_grad = True
        unfrozen += 1

if unfrozen == 0:
    available = sorted({n.split('.')[0] for n, _ in fmri_enc.named_parameters()})
    raise ValueError(f"No params matched '{TRAINABLE_LAYER}'. Top-level names: {available}")

total  = sum(p.numel() for p in fmri_enc.parameters())
active = sum(p.numel() for p in fmri_enc.parameters() if p.requires_grad)
print(f"Trainable: {active:,} / {total:,} params ({100*active/total:.2f}%) in '{TRAINABLE_LAYER}'")

# ── Optimizer ─────────────────────────────────────────────────────────────────
optimizer = torch.optim.Adam(
    [p for p in fmri_enc.parameters() if p.requires_grad],
    lr=1e-4,
)
loss_fn = nn.MSELoss()

# ── Training loop ─────────────────────────────────────────────────────────────
fmri_enc.train()

for epoch in range(5):
    for batch in train_loader:   # your DataLoader here
        inputs, targets = batch
        optimizer.zero_grad()
        out = fmri_enc(inputs)
        loss = loss_fn(out, targets)
        loss.backward()
        optimizer.step()
    print(f"Epoch {epoch+1}  loss={loss.item():.5f}")

torch.save(fmri_enc.state_dict(), f"tribe_finetuned_{TRAINABLE_LAYER.replace('.','_')}.pt") """